export const UPDATE_RECIPE="UPDATE_RECIPE"
export const ADD_RECIPE="ADD_RECIPE"
export const GET_RECIPE="GET_RECIPE"
export const DELETE_RECIPE="DELETE_RECIPE"
export const ADD_USER="ADD_USER"
export const GET_CATEGORY="GET_CATEGORY"
export const ADD_CATEGORY="ADD_CATEGORY"
export const GET_SHOPPINGLIST="GET_SHOPPINGLIST"

export const GET_INGRIDIENT="GET_INGRIDIENT"

export const ADD_PRODUCT="ADD_PRODUCT"
export const EDIT_PRODUCT="EDIT_PRODUCT"
export const DELETE_PRODUCT="DELETE_PRODUCT"